name: Keep Render Server Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:       # Allow manual trigger if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping to Render Server
        run: |
         curl -sSf -X POST https://tds-solver-rcfv.onrender.com/api -F "ping=true" 
